<h3 style='color:purple' align='center'>KFolds cross validation</h3>

**Iris dataset from sklearn**

In [149]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
import numpy as np
from sklearn.datasets import load_iris
iris = load_iris()

In [150]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

**Train and the model and prediction**

In [151]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

In [152]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [153]:
get_score(LogisticRegression(),X_train,X_test,y_train,y_test)

C:\Users\THINKUP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9333333333333333

In [154]:
get_score(SVC(C=10),X_train,X_test,y_train,y_test)

0.9777777777777777

In [155]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9333333333333333

In [135]:
#from sklearn.model_selection import KFold
#folds = KFold(n_splits=3)

In [136]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [137]:
scores_lr = []
scores_svc = []
scores_rf = []

In [138]:
for train_index,test_index in folds.split(iris.data,iris.target):
    X_train,X_test,y_train,y_test = iris.data[train_index],iris.data[test_index],iris.target[train_index],iris.target[test_index]
    scores_lr.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
    scores_svc.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

C:\Users\THINKUP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [139]:
scores_lr

[0.98, 0.96, 0.98]

In [140]:
scores_svc

[0.96, 0.98, 0.94]

In [141]:
scores_rf

[0.98, 0.94, 0.96]

In [142]:
# Calculate the mean scores
mean_lr_score = np.mean(scores_lr)
mean_svc_score = np.mean(scores_svc)
mean_rf_score = np.mean(scores_rf)

In [144]:
print("the mean of logistic regression scores is {:.2f}, the mean of SVC score is {:.2f} and the mean of Random forest scores is {:.2f}".format(mean_lr_score,mean_svc_score,mean_rf_score))

the mean of logistic regression scores is 0.97, the mean of SVC score is 0.96 and the mean of Random forest scores is 0.96


In [156]:
from sklearn.model_selection import cross_val_score

In [157]:
cross_val_score(LogisticRegression(),iris.data,iris.target)

C:\Users\THINKUP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [158]:
cross_val_score(SVC(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [159]:
cross_val_score(RandomForestClassifier(),iris.data,iris.target)

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])